name       : cdrdao
version    : 1.2.3
release    : 2
source     :
    - https://nchc.dl.sourceforge.net/project/cdrdao/cdrdao/1.2.3/cdrdao-1.2.3.tar.bz2 : 8193cb8fa6998ac362c55807e89ad0b3c63edc6b01afaeb3d5042519527fb75e
license    : GPL-2.0
component  : programming
summary    : Records audio or data CD-Rs in disk-at-once (DAO) mode
description: |
    Cdrdao records audio or data CD-Rs in disk-at-once (DAO) mode based on a textual description of the CD contents (toc-file).
builddeps  :
    - pkgconfig(vorbis)
    - lame-devel
    - libmad-devel
setup      : |
    %apply_patches
    %configure --with-mp3-support \
               --with-ogg-support
build      : |
    %make
install    : |
    %make_install
